name: CI/CD FlakyDoctor
description: GitHub Action for FlakyDoctor
author: Quint van Oorschot

runs:
  using: composite
  steps:

    - name: Locate action directory
      id: locate
      shell: bash
      run: |
        set -euo pipefail
        echo "root=${GITHUB_ACTION_PATH:-$PWD}" >> "$GITHUB_OUTPUT"

    - name: Link action into workspace
      shell: bash
      run: |
        set -euo pipefail
        ROOT="${{ steps.locate.outputs.root }}"
        TARGET="$GITHUB_WORKSPACE/CICD-FlakyDoctor"
        rm -rf "$TARGET"
        ln -s "$ROOT" "$TARGET"

    - name: Generate tests.csv for FlakyDoctor
      shell: bash
      env:
        SRC_PATH: src/test/java
      run: |
        set -euo pipefail
        ROOT="${{ steps.locate.outputs.root }}"

        echo "Generating tests.csv in $ROOT"
        ACTION_DIR="$ROOT"
        export ACTION_DIR SRC_PATH

        python3 "$GITHUB_WORKSPACE/.github/workflow-scripts/generate_tests_csv.py"

    - name: Run CICD FlakyDoctor
      shell: bash
      run: |
        set -e
        ROOT="${{ steps.locate.outputs.root }}"
        SCRIPT="$ROOT/CICD-FlakyDoctor.py"

        if [ ! -f "$SCRIPT" ]; then
          echo "ERROR: $SCRIPT not found in $ROOT"
          ls -la "$ROOT"
          exit 1
        fi

        echo "Running: python3 \"$SCRIPT\""
        python3 "$SCRIPT"