name: CI/CD FlakyDoctor
description: GitHub Action for FlakyDoctor
author: Quint van Oorschot

inputs:
  openai_api_key:
    description: "OpenAI key (optional if set in env)"
    required: false

runs:
  using: composite
  steps:
    - name: Export API key
      shell: bash
      run: |
        if [ -n "${{ inputs.openai_api_key }}" ]; then
          echo "OPENAI_API_KEY=${{ inputs.openai_api_key }}" >> "$GITHUB_ENV"
        fi

        echo "Using tests.csv at: $CSV"
        echo "FLAKYDOCTOR_TESTS_CSV=$CSV" >> "$GITHUB_ENV"

    - name: Run CICD FlakyDoctor
      shell: bash
      run: |
        set -euo pipefail
        python3 "$GITHUB_ACTION_PATH/CICD-FlakyDoctor.py"
